name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Generate Version
        id: gitversion
        run: gitversion /output json /showvariable FullSemVer

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Create NuGet package
        run: dotnet pack --configuration Release /p:PackageVersion=${{ steps.gitversion.outputs.FullSemVer }}

      - name: Publish NuGet package
        run: dotnet nuget push ./src/VisaoPkg.Gravatar/bin/Release/VisaoPkg.Gravatar.${{ steps.gitversion.outputs.FullSemVer }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
